src/objects/Trigger_Handler_Method__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_of_execution__c</fullName>
        <label>Order of execution</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger_Event_Type__c</fullName>
        <label>Trigger Event Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BEFORE_INSERT</fullName>
                    <default>true</default>
                    <label>Before insert</label>
                </value>
                <value>
                    <fullName>AFTER_INSERT</fullName>
                    <label>After insert</label>
                </value>
                <value>
                    <fullName>BEFORE_UPDATE</fullName>
                    <label>Before update</label>
                </value>
                <value>
                    <fullName>AFTER_UPDATE</fullName>
                    <label>After update</label>
                </value>
                <value>
                    <fullName>BEFORE_DELETE</fullName>
                    <label>Before delete</label>
                </value>
                <value>
                    <fullName>AFTER_DELETE</fullName>
                    <label>After delete</label>
                </value>
                <value>
                    <fullName>AFTER_UNDELETE</fullName>
                    <label>After undelete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trigger_Handler_Name__c</fullName>
        <label>Trigger Handler Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Handler Method</label>
    <pluralLabel>Trigger Handler Methods</pluralLabel>
</CustomObject>

src/objects/Trigger_Handler_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_After_Delete_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is After Delete Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_After_Insert_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is After Insert Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_After_Undelete_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is After Undelete Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_After_Update_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is After Update Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Before_Delete_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Before Delete Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Before_Insert_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Before Insert Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Before_Update_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Before Update Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Globally_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Globally Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler Settings</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

src/classes/TriggerHandlerMetadataProvider.cls
public class TriggerHandlerMetadataProvider {
    public List<Trigger_Handler_Method__mdt> getHandlerMethods(String triggerHandlerName,
                                                               System.TriggerOperation triggerOperation) {
        return [
            SELECT Id,
                   DeveloperName,
                   Order_of_execution__c
            FROM Trigger_Handler_Method__mdt
            WHERE Trigger_Handler_Name__c = :triggerHandlerName
            AND Trigger_Event_Type__c = :triggerOperation.name()
            AND Is_Enabled__c = true
        ];
    }

    public List<Trigger_Handler_Settings__mdt> getHandlerSettings(String triggerHandlerName) {
        return [
            SELECT Id,
                   Is_Globally_Enabled__c,
                   Is_Before_Insert_Enabled__c,
                   Is_After_Insert_Enabled__c,
                   Is_Before_Update_Enabled__c,
                   Is_After_Update_Enabled__c,
                   Is_Before_Delete_Enabled__c,
                   Is_After_Delete_Enabled__c,
                   Is_After_Undelete_Enabled__c
            FROM Trigger_Handler_Settings__mdt
            WHERE DeveloperName = :triggerHandlerName
        ];
    }
}